### ISSUE TITLE
Масло масляное

### ISSUE THREAD

**Issue by phoenixweiss** [MeldyTheCoder/mysql_hw#1]
На самом деле ничего страшного, но QNIQUE тут не нужен:
https://github.com/MeldyTheCoder/mysql_hw/blob/592443fe9ae3360f36280951f5b7799c8cb4fe99/homework_1.sql#LL2C25-L2C25

Причина — ты уже указываешь что это первичный ключ, и любая SQL-СУБД (если только не какая-то древняя или явно экзотическая) уже на этом основании ставит принудительную проверку уникальности, т.к. первичный ключ всегда уникален.

**Comment by MeldyTheCoder** [comment]
Ну, да. Но мне показалось, что в строчке ниже, помимо упоминания первичного ключа, идет прям акцент на уникальность:

`id — первичный ключ, не может принимать значение NULL, должен быть уникальным (опционально можете добавить автоматическую инкрементацию)`

Вдруг автопроверка бы не прошла, если бы я не указал UNIQUE. А так-то да, смысла от UNIQUE особо нет.
